### ISSUE TITLE
Auto-generated pki/secret.key is world-readable by default

### ISSUE THREAD

**Issue by elessard-genetec** [hughsie/libjcat#129]
Hello, was wondering if the `<jcat_engine_get_keyring_path>/pki/secret.key` private key that is generated by the `jcat_pkcs7_engine_self_sign` function when that file does not already exist should be created "owner-readable only" (i.e. with mode 600) ? Currently, it's created with mode 666, given `jcat_pkcs7_engine_self_sign` calls `jcat_set_contents_bytes` which call `g_file_set_contents` which create the file with mode 666.

This was seen while using libjcat through fwupd.

**Comment by hughsie** [comment]
In fwupd the keyring secret key is only used to identify the machine, it's not in any way secret really. That said, if you wanted to submit a patch to change libjcat to use g_file_set_contents_full I'd merge it.

**Comment by elessard-genetec** [comment]
Great, thanks for the quick reply.
