### ISSUE TITLE
Decrease meson version

### ISSUE THREAD

**Issue by superm1** [hughsie/libjcat#21]
In https://github.com/hughsie/libjcat/commit/d6dc3e90b0c805cc50bff9d1d1b87ff575e53769 the meson version was bumped to 0.52.  This has broken LGTM CI on fwupd since it only has meson 0.51.2.  Can it be bumped down back to 0.51 instead?

**Comment by hughsie** [comment]
I believe that was for `environment()` i.e. deliberate. Is there a way we can build a new meson in LGTM using pip or unstable perhaps? I think LGTM is just Debian stable under the hood.

**Comment by smcv** [comment]
> I think LGTM is just Debian stable under the hood

It seems to be Ubuntu 19.10 'eoan', i.e. their latest short-term-supported release (analogous to Fedora), rather than using something longer-term-supported (Debian stable, Ubuntu LTS, RHEL/CentOS) like most other CI systems seem to do.
