### ISSUE TITLE
Change binary name

### ISSUE THREAD

**Issue by superm1** [hughsie/libjcat#3]
It seems that at least in Debian and Ubuntu there is a package called `sleuthkit` that provides the binary `jcat`.  Would you consider renaming it to `jcat-tool`, or `json-catalog` (or anything else similar)?

Otherwise it's going to mean having to have a conflicts relationship to `sleuthkit` so people can never install them side by side.

**Comment by superm1** [comment]
Oh wait, you did rename it to `jcatutil`, nvm

**Comment by superm1** [comment]
I think I would still prefer to see `jcat-tool` though (to match `fwupdtool`, `xb-tool` and similar)

**Comment by hughsie** [comment]
`jcat-tool` WFM.
