### ISSUE TITLE
gzipping overhead

### ISSUE THREAD

**Issue by abitrolly** [hughsie/libjcat#36]
How serious is the problem that gzip is trying to solve?

I see that JSON tools don't really see gzip compression as something that belongs to the ecosystem
https://github.com/stedolan/jq/issues/968

**Comment by hughsie** [comment]
> How serious is the problem that gzip is trying to solve

That gzip makes the final files much smaller, and the jcat file is downloaded millions of times per day... and when more people upgrade to fwupd 1.4.x it'll be hundreds of millions of times per day...

**Comment by abitrolly** [comment]
@hughsie why people need to download .jcat file alone without the firmware itself? Do they download all .jcat files and parse them to find the firmware what they need?

**Comment by hughsie** [comment]
In fwupd 1.4.0 the tiny jcat file is downloaded, and only if the file has changed we download the much larger catalog. The gzip is by design, sorry.

**Comment by abitrolly** [comment]
@hughsie how does `fwupd` know which jcat file to download?

**Comment by hughsie** [comment]
It looks at https://github.com/fwupd/fwupd/blob/master/data/remotes.d/lvfs.conf#L6 and apends `.jcat`.

**Comment by abitrolly** [comment]
So it first downloads 343Kb of https://cdn.fwupd.org/downloads/firmware.xml.gz and then a few files from listed there?

I don't see how that saves space or bandwidth. The bandwidth could be saved by using `Accept-Encoding: gzip, deflate` while downloading files. The XML format can also be transformed into more human readable and space efficient one.

If the format was the same, it might be possible to maintain "split index" - one tree listing only ids, and then many leaf files/records that can be directly merged into the main structure by recursive copy.
